### ISSUE TITLE
guys, build.bat give me an error ("data.zip" not found), what can i do?

### ISSUE THREAD

**Issue by EvilPudding** [EvilPudding/candle#11]
guys, build.bat give me an error ("data.zip" not found), what can i do?

_Originally posted by @ilyzmmm in https://github.com/EvilPudding/candle/issues/10#issuecomment-1096831512_

**Comment by EvilPudding** [comment]
@ilyzmmm Are you running the sample project? If so, could you provide me with a complete log of the build?

**Comment by ilyzmmm** [comment]
@EvilPudding oh, no, thank you, for some reason i was sure that engine have to be compiled at first without sample project xD

**Comment by EvilPudding** [comment]
:+1:
