### ISSUE TITLE
No indexed sauce named...

### ISSUE THREAD

**Issue by ghost** [EvilPudding/candle#3]
After compiling the example code, that is twin_peaks, I get an executable that after running says:
```

GL Vendor : NVIDIA Corporation
GL Renderer : GeForce GTX 980/PCIe/SSE2
GL Version (string) : 4.4.0 NVIDIA 410.73
GL Version (integer) : 4.4
GLSL Version : 4.40 NVIDIA via Cg compiler
loading resauces/models/floor.obj
loading resauces/models/cloth.obj
no indexed sauce named tile_diffuse
no indexed sauce named tile_normal
no indexed sauce named velvet_diffuse
no indexed sauce named velvet_normal
no indexed sauce named stone3_diffuse
loading resauces/models/venus.obj

```

Also, the render screen is simply black, though GUI elements are visible.
![2018-11-08-151147_1920x1200_scrot](https://user-images.githubusercontent.com/43107265/48203807-5491b180-e360-11e8-80fe-1afd78914f9f.png)

**Comment by EvilPudding** [comment]
Thanks for bringing this to my attention, if you pull, is it fixed now?

**Comment by EvilPudding** [comment]
If the screen is still black, make sure you have the latest candle version with:
```
git submodule update --init --recursive
```

**Comment by ghost** [comment]
I'll try right now.

**Comment by ghost** [comment]
Thanks, it works right now.
![2018-11-08-190624_1920x1200_scrot](https://user-images.githubusercontent.com/43107265/48218125-13f66000-e381-11e8-844b-a1ad18894b0b.png)
Though, as you can see, the resolution seems to be small. Also, I can't tell what is that entity on the left

**Comment by EvilPudding** [comment]
It's a sprite, for testing, somehow your screenshot looks like it's from an outdated version, I'm not sure what's happening. Can you show me what commit candle, twinpeaks and nuklear are currently on?

**Comment by ghost** [comment]
Sure, give me a moment

**Comment by ghost** [comment]
The current commit of twinpeaks is `commit e6143174a9fc2fe791160bf89b4f422c271f5909`
Also, I use Void Linux here.
Moreover, I use latest versions of candle, twinpeaks and nuclear. Straight from corresponding github repos, downloaded by --recursive option.

**Comment by ghost** [comment]
Nevermind. I ran `git submodule update --init --recursive`and the resolution is normal now

**Comment by EvilPudding** [comment]
hmm, it should do that automatically when you clone recursively, and I think it should update when you pull the main repo, something is wrong. Anyway, if you see anything wrong or want to suggest any kind of improvements, I'll be happy to hear from you!
