### ISSUE TITLE
Missing -llua on ubuntu 18.04

### ISSUE THREAD

**Issue by deno750** [EvilPudding/candle#4]
Hello, when I try to make, the compilation ends up with an error which shows that -llua cannot be found. What library is needed exactly?

**Comment by EvilPudding** [comment]
Can you tell me which commit you're on in candle? To make sure it's updated try:

`
git submodule update --init --recursive
`

**Comment by EvilPudding** [comment]
Ignore my last comment, I just checked and the linker flag is there in the `Makefile`, my bad. Is it fixed with the last commit? Thanks for testing and finding this.

**Comment by deno750** [comment]
Yeah thanks now it's working fine :)
