### ISSUE TITLE
Segmentation fault when trying to use "pick texture"

### ISSUE THREAD

**Issue by jfpmonteiro** [EvilPudding/candle#5]
Pressing any of the "pick texture" buttons gives a segmentation fault.

**Comment by EvilPudding** [comment]
As it stands, the only way to pick files requires the [filepicker.candle](https://github.com/EvilPudding/filepicker.candle) module. A fallback using nuklear is planned, but has not been implemented yet. Maybe using [cxong/tinydir](https://github.com/cxong/tinydir).

**Comment by EvilPudding** [comment]
I've prevented the segmentation fault and added a warning.

**Comment by jfpmonteiro** [comment]
I assumed the need for filepicker.candle module.
But add-ons functionality shouldn't be visible to the user from an UX perspective. Unless the same is present.

**Comment by EvilPudding** [comment]
> I assumed the need for filepicker.candle module.

Again, this isn't supposed to be a need, it's temporary until I have a file picker built on nuklear. As it stands, modules can get priority over specific events which is the only way for them to extend candle processes. I am open to suggestions of other ways of doing this, but the event being called to pick a file isn't specific to the *filepicker* module, at least it isn't supposed to be. Any module or even the main program can listen to that event.
